// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: db_service.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message definitions
type User struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email               string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username            string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash        string                 `protobuf:"bytes,4,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	IsActive            bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsEmailVerified     bool                   `protobuf:"varint,6,opt,name=is_email_verified,json=isEmailVerified,proto3" json:"is_email_verified,omitempty"`
	Role                string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	StorageQuota        int64                  `protobuf:"varint,8,opt,name=storage_quota,json=storageQuota,proto3" json:"storage_quota,omitempty"`
	UsedSpace           int64                  `protobuf:"varint,9,opt,name=used_space,json=usedSpace,proto3" json:"used_space,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FailedLoginAttempts int32                  `protobuf:"varint,12,opt,name=failed_login_attempts,json=failedLoginAttempts,proto3" json:"failed_login_attempts,omitempty"`
	LockedUntil         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=locked_until,json=lockedUntil,proto3" json:"locked_until,omitempty"`
	LastLogin           *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_db_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetIsEmailVerified() bool {
	if x != nil {
		return x.IsEmailVerified
	}
	return false
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetStorageQuota() int64 {
	if x != nil {
		return x.StorageQuota
	}
	return 0
}

func (x *User) GetUsedSpace() int64 {
	if x != nil {
		return x.UsedSpace
	}
	return 0
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetFailedLoginAttempts() int32 {
	if x != nil {
		return x.FailedLoginAttempts
	}
	return 0
}

func (x *User) GetLockedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.LockedUntil
	}
	return nil
}

func (x *User) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_db_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRequest) Reset() {
	*x = EmailRequest{}
	mi := &file_db_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRequest) ProtoMessage() {}

func (x *EmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRequest.ProtoReflect.Descriptor instead.
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{2}
}

func (x *EmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernameRequest) Reset() {
	*x = UsernameRequest{}
	mi := &file_db_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernameRequest) ProtoMessage() {}

func (x *UsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernameRequest.ProtoReflect.Descriptor instead.
func (*UsernameRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{3}
}

func (x *UsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UpdatePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_db_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePasswordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePasswordRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type UpdateUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsernameRequest) Reset() {
	*x = UpdateUsernameRequest{}
	mi := &file_db_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameRequest) ProtoMessage() {}

func (x *UpdateUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameRequest.ProtoReflect.Descriptor instead.
func (*UpdateUsernameRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUsernameRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UpdateEmailVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsVerified    bool                   `protobuf:"varint,2,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailVerificationRequest) Reset() {
	*x = UpdateEmailVerificationRequest{}
	mi := &file_db_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailVerificationRequest) ProtoMessage() {}

func (x *UpdateEmailVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailVerificationRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailVerificationRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEmailVerificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEmailVerificationRequest) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

type UpdateFailedLoginAttemptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Attempts      int32                  `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFailedLoginAttemptsRequest) Reset() {
	*x = UpdateFailedLoginAttemptsRequest{}
	mi := &file_db_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFailedLoginAttemptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFailedLoginAttemptsRequest) ProtoMessage() {}

func (x *UpdateFailedLoginAttemptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFailedLoginAttemptsRequest.ProtoReflect.Descriptor instead.
func (*UpdateFailedLoginAttemptsRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateFailedLoginAttemptsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFailedLoginAttemptsRequest) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type UpdateLockedUntilRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LockedUntil   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=locked_until,json=lockedUntil,proto3" json:"locked_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLockedUntilRequest) Reset() {
	*x = UpdateLockedUntilRequest{}
	mi := &file_db_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLockedUntilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLockedUntilRequest) ProtoMessage() {}

func (x *UpdateLockedUntilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLockedUntilRequest.ProtoReflect.Descriptor instead.
func (*UpdateLockedUntilRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateLockedUntilRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLockedUntilRequest) GetLockedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.LockedUntil
	}
	return nil
}

type UpdateStorageUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UsedSpace     int64                  `protobuf:"varint,2,opt,name=used_space,json=usedSpace,proto3" json:"used_space,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStorageUsageRequest) Reset() {
	*x = UpdateStorageUsageRequest{}
	mi := &file_db_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStorageUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStorageUsageRequest) ProtoMessage() {}

func (x *UpdateStorageUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStorageUsageRequest.ProtoReflect.Descriptor instead.
func (*UpdateStorageUsageRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateStorageUsageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStorageUsageRequest) GetUsedSpace() int64 {
	if x != nil {
		return x.UsedSpace
	}
	return 0
}

type ExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsResponse) Reset() {
	*x = ExistsResponse{}
	mi := &file_db_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsResponse) ProtoMessage() {}

func (x *ExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsResponse.ProtoReflect.Descriptor instead.
func (*ExistsResponse) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{10}
}

func (x *ExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_db_service_proto protoreflect.FileDescriptor

const file_db_service_proto_rawDesc = "" +
	"\n" +
	"\x10db_service.proto\x12\tdbservice\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb2\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x04 \x01(\tR\fpasswordHash\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12*\n" +
	"\x11is_email_verified\x18\x06 \x01(\bR\x0fisEmailVerified\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x12#\n" +
	"\rstorage_quota\x18\b \x01(\x03R\fstorageQuota\x12\x1d\n" +
	"\n" +
	"used_space\x18\t \x01(\x03R\tusedSpace\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x122\n" +
	"\x15failed_login_attempts\x18\f \x01(\x05R\x13failedLoginAttempts\x12=\n" +
	"\flocked_until\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vlockedUntil\x129\n" +
	"\n" +
	"last_login\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\"\x18\n" +
	"\x06UserID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\fEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"-\n" +
	"\x0fUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"L\n" +
	"\x15UpdatePasswordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\"C\n" +
	"\x15UpdateUsernameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"Q\n" +
	"\x1eUpdateEmailVerificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vis_verified\x18\x02 \x01(\bR\n" +
	"isVerified\"N\n" +
	" UpdateFailedLoginAttemptsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\battempts\x18\x02 \x01(\x05R\battempts\"i\n" +
	"\x18UpdateLockedUntilRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\flocked_until\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlockedUntil\"J\n" +
	"\x19UpdateStorageUsageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"used_space\x18\x02 \x01(\x03R\tusedSpace\"(\n" +
	"\x0eExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2\xcf\a\n" +
	"\tDBService\x122\n" +
	"\n" +
	"CreateUser\x12\x0f.dbservice.User\x1a\x11.dbservice.UserID\"\x00\x123\n" +
	"\vGetUserByID\x12\x11.dbservice.UserID\x1a\x0f.dbservice.User\"\x00\x12<\n" +
	"\x0eGetUserByEmail\x12\x17.dbservice.EmailRequest\x1a\x0f.dbservice.User\"\x00\x127\n" +
	"\n" +
	"UpdateUser\x12\x0f.dbservice.User\x1a\x16.google.protobuf.Empty\"\x00\x12L\n" +
	"\x0eUpdatePassword\x12 .dbservice.UpdatePasswordRequest\x1a\x16.google.protobuf.Empty\"\x00\x12L\n" +
	"\x0eUpdateUsername\x12 .dbservice.UpdateUsernameRequest\x1a\x16.google.protobuf.Empty\"\x00\x12^\n" +
	"\x17UpdateEmailVerification\x12).dbservice.UpdateEmailVerificationRequest\x1a\x16.google.protobuf.Empty\"\x00\x12>\n" +
	"\x0fUpdateLastLogin\x12\x11.dbservice.UserID\x1a\x16.google.protobuf.Empty\"\x00\x12b\n" +
	"\x19UpdateFailedLoginAttempts\x12+.dbservice.UpdateFailedLoginAttemptsRequest\x1a\x16.google.protobuf.Empty\"\x00\x12R\n" +
	"\x11UpdateLockedUntil\x12#.dbservice.UpdateLockedUntilRequest\x1a\x16.google.protobuf.Empty\"\x00\x12T\n" +
	"\x12UpdateStorageUsage\x12$.dbservice.UpdateStorageUsageRequest\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\x10CheckEmailExists\x12\x17.dbservice.EmailRequest\x1a\x19.dbservice.ExistsResponse\"\x00\x12N\n" +
	"\x13CheckUsernameExists\x12\x1a.dbservice.UsernameRequest\x1a\x19.dbservice.ExistsResponse\"\x00B7Z5homecloud-auth-service/internal/transport/grpc/protosb\x06proto3"

var (
	file_db_service_proto_rawDescOnce sync.Once
	file_db_service_proto_rawDescData []byte
)

func file_db_service_proto_rawDescGZIP() []byte {
	file_db_service_proto_rawDescOnce.Do(func() {
		file_db_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_db_service_proto_rawDesc), len(file_db_service_proto_rawDesc)))
	})
	return file_db_service_proto_rawDescData
}

var file_db_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_db_service_proto_goTypes = []any{
	(*User)(nil),                             // 0: dbservice.User
	(*UserID)(nil),                           // 1: dbservice.UserID
	(*EmailRequest)(nil),                     // 2: dbservice.EmailRequest
	(*UsernameRequest)(nil),                  // 3: dbservice.UsernameRequest
	(*UpdatePasswordRequest)(nil),            // 4: dbservice.UpdatePasswordRequest
	(*UpdateUsernameRequest)(nil),            // 5: dbservice.UpdateUsernameRequest
	(*UpdateEmailVerificationRequest)(nil),   // 6: dbservice.UpdateEmailVerificationRequest
	(*UpdateFailedLoginAttemptsRequest)(nil), // 7: dbservice.UpdateFailedLoginAttemptsRequest
	(*UpdateLockedUntilRequest)(nil),         // 8: dbservice.UpdateLockedUntilRequest
	(*UpdateStorageUsageRequest)(nil),        // 9: dbservice.UpdateStorageUsageRequest
	(*ExistsResponse)(nil),                   // 10: dbservice.ExistsResponse
	(*timestamppb.Timestamp)(nil),            // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                    // 12: google.protobuf.Empty
}
var file_db_service_proto_depIdxs = []int32{
	11, // 0: dbservice.User.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: dbservice.User.updated_at:type_name -> google.protobuf.Timestamp
	11, // 2: dbservice.User.locked_until:type_name -> google.protobuf.Timestamp
	11, // 3: dbservice.User.last_login:type_name -> google.protobuf.Timestamp
	11, // 4: dbservice.UpdateLockedUntilRequest.locked_until:type_name -> google.protobuf.Timestamp
	0,  // 5: dbservice.DBService.CreateUser:input_type -> dbservice.User
	1,  // 6: dbservice.DBService.GetUserByID:input_type -> dbservice.UserID
	2,  // 7: dbservice.DBService.GetUserByEmail:input_type -> dbservice.EmailRequest
	0,  // 8: dbservice.DBService.UpdateUser:input_type -> dbservice.User
	4,  // 9: dbservice.DBService.UpdatePassword:input_type -> dbservice.UpdatePasswordRequest
	5,  // 10: dbservice.DBService.UpdateUsername:input_type -> dbservice.UpdateUsernameRequest
	6,  // 11: dbservice.DBService.UpdateEmailVerification:input_type -> dbservice.UpdateEmailVerificationRequest
	1,  // 12: dbservice.DBService.UpdateLastLogin:input_type -> dbservice.UserID
	7,  // 13: dbservice.DBService.UpdateFailedLoginAttempts:input_type -> dbservice.UpdateFailedLoginAttemptsRequest
	8,  // 14: dbservice.DBService.UpdateLockedUntil:input_type -> dbservice.UpdateLockedUntilRequest
	9,  // 15: dbservice.DBService.UpdateStorageUsage:input_type -> dbservice.UpdateStorageUsageRequest
	2,  // 16: dbservice.DBService.CheckEmailExists:input_type -> dbservice.EmailRequest
	3,  // 17: dbservice.DBService.CheckUsernameExists:input_type -> dbservice.UsernameRequest
	1,  // 18: dbservice.DBService.CreateUser:output_type -> dbservice.UserID
	0,  // 19: dbservice.DBService.GetUserByID:output_type -> dbservice.User
	0,  // 20: dbservice.DBService.GetUserByEmail:output_type -> dbservice.User
	12, // 21: dbservice.DBService.UpdateUser:output_type -> google.protobuf.Empty
	12, // 22: dbservice.DBService.UpdatePassword:output_type -> google.protobuf.Empty
	12, // 23: dbservice.DBService.UpdateUsername:output_type -> google.protobuf.Empty
	12, // 24: dbservice.DBService.UpdateEmailVerification:output_type -> google.protobuf.Empty
	12, // 25: dbservice.DBService.UpdateLastLogin:output_type -> google.protobuf.Empty
	12, // 26: dbservice.DBService.UpdateFailedLoginAttempts:output_type -> google.protobuf.Empty
	12, // 27: dbservice.DBService.UpdateLockedUntil:output_type -> google.protobuf.Empty
	12, // 28: dbservice.DBService.UpdateStorageUsage:output_type -> google.protobuf.Empty
	10, // 29: dbservice.DBService.CheckEmailExists:output_type -> dbservice.ExistsResponse
	10, // 30: dbservice.DBService.CheckUsernameExists:output_type -> dbservice.ExistsResponse
	18, // [18:31] is the sub-list for method output_type
	5,  // [5:18] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_db_service_proto_init() }
func file_db_service_proto_init() {
	if File_db_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_db_service_proto_rawDesc), len(file_db_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_db_service_proto_goTypes,
		DependencyIndexes: file_db_service_proto_depIdxs,
		MessageInfos:      file_db_service_proto_msgTypes,
	}.Build()
	File_db_service_proto = out.File
	file_db_service_proto_goTypes = nil
	file_db_service_proto_depIdxs = nil
}
