database:
  host: localhost
  port: 5432
  
server:
  host: "0.0.0.0"
  port: 8080

grpcAuthServer:
  host: 0.0.0.0
  port: 50051

jwt:
  secret_key: "your-super-secret-jwt-key-change-in-production"
  expiration: "24h"

verification:
  secret_key: "your-super-secret-verification-key-change-in-production"
  expiration: "24h"

logger:
  level: "info"
  development: true
  encoding: "json"
  outputPaths: ["stdout"]
  errorOutputPaths: ["stderr"]
  encoderConfig:
    messageKey: "message"
    levelKey: "level"
    timeKey: "timestamp"
    nameKey: "logger"
    callerKey: "caller"
    functionKey: "func"
    stacktraceKey: "stacktrace"
    lineEnding: "\n"
    levelEncoder: "lowercase"
    timeEncoder: "iso8601"
    durationEncoder: "string"
    callerEncoder: "short"
    encodeTime: "iso8601"